### ISSUE TITLE
fda的loss没有相加

### ISSUE THREAD

**Issue by zhou-rui1** [thuml/Transfer-Learning-Library#101]
Hi，fda应该是3个loss共同作用吧，在这里好像是单独作用的

`   criterion = torch.nn.CrossEntropyLoss(ignore_index=args.ignore_label).to(device)`

`        y_s = model(x_s)
        pred_s = interp(y_s)
        loss_cls_s = criterion(pred_s, label_s)
        loss_cls_s.backward()
        y_t = model(x_t)
        pred_t = interp(y_t)
        loss_cls_t = criterion(pred_t, label_t)
        loss_entropy_t = robust_entropy(y_t, args.ita)
        (args.entropy_weight * loss_entropy_t).backward()`

**Comment by tsingcbx99** [comment]
先相加后backward和两次分别backward是等价的，因为pytorch会自动累计每一个tensor的梯度。可以去参考一下pytorch的官方教程~
