### ISSUE TITLE
Hi, I beg you to re-implement the STA method proposed by your group~

### ISSUE THREAD

**Issue by Jing--Li** [thuml/Transfer-Learning-Library#103]
The method STA was proposed by your group in the CVPR2019 paper named "Separate to Adapt: Open Set Domain Adaptation via Progressive Separation", it still achieves SOTA results nowadays. What a good method. However, it was not implemented well enough in the original open-sourced code by the original authors, because its readability is not very good which results in confusion.

So I beg you to re-implement the STA method, Thank you!

**Comment by JunguangJiang** [comment]
Maybe you should ask the author of this paper for better implementation?
