### ISSUE TITLE
README.md可以加入中文描述吗

### ISSUE THREAD

**Issue by liuyang77886** [thuml/Transfer-Learning-Library#107]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tsingcbx99** [comment]
指的是提issue的过程中可以加入中文描述吗？当然可以，不过考虑到我们库的受众还是更推荐使用英文（就当练英语了，不亏）

**Comment by liuyang77886** [comment]
抱歉，我的意思是README.md加入中文版

**Comment by JunguangJiang** [comment]
感谢你的建议!我们会在下一个release中加入中文版本的readme.md
