### ISSUE TITLE
Can't run rightly

### ISSUE THREAD

**Issue by WUzhusihan** [thuml/Transfer-Learning-Library#11]
I've installed dalib and do experiments according to the GitHub example. The question is it can't run rightly, always stuck in the beginning.
![image](https://user-images.githubusercontent.com/43961541/91789029-4b15bf80-ec40-11ea-823f-29ec6692b44a.png)
It seems like the dataset is not read in because the GPU memory is not used. 
![image](https://user-images.githubusercontent.com/43961541/91789200-bc557280-ec40-11ea-9d02-6ffecb3f00c5.png)
And I've checked the dataset format as described in the API documentation.
 So I want to get some help. Thanks.

**Comment by WUzhusihan** [comment]
I further identified the data reading problem and the model. Everything seems to be ok. But it always stops in the beginning.
![image](https://user-images.githubusercontent.com/43961541/91791784-9763fe00-ec46-11ea-8eb1-c67230800371.png)

**Comment by microhhh** [comment]
What's your torchvision version?

**Comment by WUzhusihan** [comment]
> What's your torchvision version?
![image](https://user-images.githubusercontent.com/43961541/91793925-3c350a00-ec4c-11ea-90d0-c8dcc7b2f4ee.png)
I created a new env with python version 3.6 and used 'pip install dalib' to install all the requirements.

**Comment by microhhh** [comment]
Try git clone the repo, and run the examples in repo root path?

**Comment by microhhh** [comment]
The problem is really the data reading, you can check your machine environment carefully.

**Comment by WUzhusihan** [comment]
> Try git clone the repo, and run the examples in repo root path?

I tried to create another env. Git clone the repo and 'pip install dalib' both work now. I don't know why. The two envs are completely the same. 
BTW, what's the meaning of the output 'data', it's always equal to zero like: 
![image](https://user-images.githubusercontent.com/43961541/91818947-482ec500-ec68-11ea-8192-4a9f58f573a4.png)

**Comment by WUzhusihan** [comment]
> The problem is really the data reading, you can check your machine environment carefully.

I tried to create another env. Git clone the repo and 'pip install dalib' both work now. I don't know why. The two envs are completely the same.
Anyhow, thanks a lot!

**Comment by microhhh** [comment]
just clone the repo, do not pip install.  And check other component like CUDA, cudnn, nvidia drivers.

**Comment by WUzhusihan** [comment]
> just clone the repo, do not pip install. And check other component like CUDA, cudnn, nvidia drivers.

Got it. Now, it works.
