### ISSUE TITLE
The accuracy of DANN, source only are unexpectedly high

### ISSUE THREAD

**Issue by veroveroxie** [thuml/Transfer-Learning-Library#110]
Hi, thanks for your great work.

I noticed that you implemention of DANN,  and source only achieved higher result than reported in other papers as shown in https://tl.thuml.ai/dalib/benchmarks/multi_source_domain_adaptation.html 

In particular, the source only is suprisingly high (DomainNet) and in fact it beats most of sota MSDA methods (they are also based on Resnet101).  Could you please share some thoughts on this observation?

**Comment by tsingcbx99** [comment]
We carefully tuned the hyper parameters of these baseline methods (DANN, source only). Among these parameters, we found that the learning rate strategy and data augmentation may have a great influence.  Following DAN, we adopt a `10x` lr strategy (if head uses lr 0.01, then backbone uses 0.001). For data augmentation, applying `RandomCrop` or `RandomResizeCrop` can be very different.

**Comment by veroveroxie** [comment]
That makes sense. Thank you.
