### ISSUE TITLE
A confusing problem in adda.py

### ISSUE THREAD

**Issue by WANGBohaO-jpg** [thuml/Transfer-Learning-Library#112]
In adda.py, the loss function about classifier has already inverse the label, why there needs a "gl"(gradient reversal layer) on 191 line ?

**Comment by thucbx99** [comment]
See line 89 of `adda.py`, gl is an instance of `WarmStartGradientLayer`, not `WarmStartGradientReverseLayer`, which means that it doesn't reverst the gradient.

**Comment by JonasZero** [comment]
> See line 89 of `adda.py`, gl is an instance of `WarmStartGradientLayer`, not `WarmStartGradientReverseLayer`, which means that it doesn't reverst the gradient.

Okay, thank you.
