### ISSUE TITLE
大佬，请问这个库没有目标检测的代码吗

### ISSUE THREAD

**Issue by yanjinwei143** [thuml/Transfer-Learning-Library#115]
大佬，库里没有这篇文章DECOUPLED ADAPTATION FOR CROSS-DOMAIN OBJECT DETECTION的代码吗

**Comment by JunguangJiang** [comment]
大部分代码都已经开源到https://github.com/thuml/Transfer-Learning-Library/tree/dev-da-object-detection/examples/domain_adaptation/object_detection这个位置了，还差文档和数据集下载没有写好（再稍微等几天）

**Comment by thucbx99** [comment]
文档和数据集下载也已经更新到 https://github.com/thuml/Transfer-Learning-Library/tree/dev-da-object-detection/examples/domain_adaptation/object_detection

**Comment by JunguangJiang** [comment]
相关代码已经合并到dev-tllib分支了，之后会统一合并到主分支
