### ISSUE TITLE
fogy_cityscape dataset convert error：The total number of index is not correct    for adaptive object detection

### ISSUE THREAD

**Issue by zyfone** [thuml/Transfer-Learning-Library#119]
hello thanks for developing this lib
i get voc style dataset of cityscape/fogy_cityscape in prepare_cityscapes_to_voc.py
but i find index of  ImageSets/Main/test.txt which only have 493 indexs ,but there are 500 in paper

**Comment by zyfone** [comment]
I know this is an object with empty labels removed, but removing the empty labels in the test will affect the final accuracy
So I want to know whether the test set in the paper removes images with empty labels
last but no least
Thanks to the authors for their open source work

**Comment by JunguangJiang** [comment]
mAP50 is calculated only when the IOU exceeds 0.5.
Since there is no ground truth in these images, the IOU cannot exceed 0.5. Thus even if there is output on these images, they are not involved in the final calculation.
Therefore, we think removing the empty labels will not affect the final accuracy.

**Comment by zyfone** [comment]
Thanks to the authors for open-source work,again。
This is very helpful for beginners.
I'm really sorry for asking such a low-level question

I listed my results hoping to be helpful to other students who have the same problem
data-augment：cyclegan

dataset：Cityscapes to Foggy Cityscapes

FOR 500

AP for bus = 0.4898
AP for bicycle = 0.3892
AP for car = 0.5262
AP for motorcycle = 0.3314
AP for person = 0.3810
AP for rider = 0.4864
AP for train = 0.4298
AP for truck = 0.2992
Mean AP = 0.4166

FOR 492
AP for bus = 0.4898
AP for bicycle = 0.3912
AP for car = 0.5262
AP for motorcycle = 0.3315
AP for person = 0.3813
AP for rider = 0.4864
AP for train = 0.4298
AP for truck = 0.2994
Mean AP = 0.4169

**Comment by zyfone** [comment]
By the way，migration between similar domains always is a difficult problem for domain adaptive object detection。
Especially in cityscape and foggy cityscape.
Using cyclegan seems like way which use target annotation，because pictures of cyclegan are very similar to the target pictures 。
**SO，Is it unreasonable to use cyclegan？**
 HTCN(Hierarchical Transferability Calibration Network)seemly like firstly introduce this data-augment in object detection。But  HTCN withou cyclegan only get 37.5 in foggy。

**Comment by JunguangJiang** [comment]
> Thanks to the authors for open-source work,again。 This is very helpful for beginners. I'm really sorry for asking such a low-level question
> 
> I listed my results hoping to be helpful to other students who have the same problem data-augment：cyclegan
> 
> dataset：Cityscapes to Foggy Cityscapes
> 
> FOR 500
> 
> AP for bus = 0.4898 AP for bicycle = 0.3892 AP for car = 0.5262 AP for motorcycle = 0.3314 AP for person = 0.3810 AP for rider = 0.4864 AP for train = 0.4298 AP for truck = 0.2992 Mean AP = 0.4166
> 
> FOR 492 AP for bus = 0.4898 AP for bicycle = 0.3912 AP for car = 0.5262 AP for motorcycle = 0.3315 AP for person = 0.3813 AP for rider = 0.4864 AP for train = 0.4298 AP for truck = 0.2994 Mean AP = 0.4169

Thanks for your question and results.

**Comment by JunguangJiang** [comment]
> By the way，migration between similar domains always is a difficult problem for domain adaptive object detection。 Especially in cityscape and foggy cityscape. Using cyclegan seems like way which use target annotation，because pictures of cyclegan are very similar to the target pictures 。 **SO，Is it unreasonable to use cyclegan？** HTCN(Hierarchical Transferability Calibration Network)seemly like firstly introduce this data-augment in object detection。But HTCN withou cyclegan only get 37.5 in foggy。

In my opinion, transfer between similar domains is much easier.

The real problem is that Cityscapes to  Foggy Cityscapes is an ill-defined task since there exists a single-to-single map between the images in the target domain and the source domain, which is not likely encountered in practical applications. (If you really encounter such occasions, you can use a simple solution like CycleGAN.)

Since previous work has used this task, we also support this task.

**Comment by zyfone** [comment]
> > By the way，migration between similar domains always is a difficult problem for domain adaptive object detection。 Especially in cityscape and foggy cityscape. Using cyclegan seems like way which use target annotation，because pictures of cyclegan are very similar to the target pictures 。 **SO，Is it unreasonable to use cyclegan？** HTCN(Hierarchical Transferability Calibration Network)seemly like firstly introduce this data-augment in object detection。But HTCN withou cyclegan only get 37.5 in foggy。
> 
> In my opinion, transfer between similar domains is much easier.
> 
> The real problem is that Cityscapes to Foggy Cityscapes is an ill-defined task since there exists a single-to-single map between the images in the target domain and the source domain, which is not likely encountered in practical applications. (If you really encounter such occasions, you can use a simple solution like CycleGAN.)
> 
> Since previous work has used this task, we also support this task.

Thank you very much. It was a great harvest

**Comment by Fly-dream12** [comment]
Is the two supported method cycleGAN and Decouple Adaptation independent with each other, by the way, where is the adversarial process in cycleGAN, does it works like HTCN? @JunguangJiang @microhhh @zyfone  Many thanks

**Comment by zyfone** [comment]
> Is the two supported method cycleGAN and Decouple Adaptation independent with each other, by the way, where is the adversarial process in cycleGAN, does it works like HTCN? @JunguangJiang @microhhh @zyfone Many thanks

cycleGAN is  a kind of method which is used to augment dataset。 clipart or cityscape，for example 。

Decouple Adaptation is a  domain adaptive obejct detection method which decouple  domain procedure to enhance Transferability and Transferability。

Therefore ，they are independent of each other。you also can use cycleGAN to get new target-like dataset in your train-set.

it works like HTCN. beause of the need of fair comparison
Fair comparison can prove validity of this paper
