### ISSUE TITLE
Sharing pre-trained models

### ISSUE THREAD

**Issue by kiranchari** [thuml/Transfer-Learning-Library#123]
**Is your feature request related to a problem? Please describe.**
Some models require a lot of resources (time, GPU) to train e.g. CycleGAN/CyCADA for CityScapes to FoggyCityscapes translation

**Describe the solution you'd like**
It would be very useful if you could share pre-trained cycleGAN and Cycada models for CityScapes to FoggyCityscapes translation. 

**Describe alternatives you've considered**
Training these models from scratch.

**Comment by JunguangJiang** [comment]
Thanks for your suggestions. We will release the pre-trained CycleGAN after re-running these experiments.
