### ISSUE TITLE
在github上下载不了domain adaptation中的object detection，请问作者什么时候可以下载？谢谢

### ISSUE THREAD

**Issue by ZhangXiufei** [thuml/Transfer-Learning-Library#126]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JunguangJiang** [comment]
切换到开发分支 https://github.com/thuml/Transfer-Learning-Library/tree/dev-tllib，然后下载就可以
