### ISSUE TITLE
Consultation on code execution problems：per_category_scores[c].append(s)   KeyError: 8

### ISSUE THREAD

**Issue by Elaine0823** [thuml/Transfer-Learning-Library#129]
Hello,
I trained the code on source-only.py successfully, but when trying to run d-adapt.py, I receive the following error.
![image](https://user-images.githubusercontent.com/77908581/163300535-a252d11b-3288-4372-a5b3-1649bcef7774.png)
I'm using my custom dataset (1 class). Does a dataset containing only one category need category_adaptation? If not, how should I remove the function of category_adaptation? Could you give me some advice on what I should do? Thanks very much.

**Comment by JunguangJiang** [comment]
If there is only one category in your problem, it is more recommended to use CycleGAN.
It would be better to use D-adapt when there are several categories.

One possible reason for this error is that you might forget to set "MODEL.ROI_HEADS.NUM_CLASSES 1" in the command line.
