### ISSUE TITLE
broken download url 

### ISSUE THREAD

**Issue by MyeongJin-Kim** [thuml/Transfer-Learning-Library#133]
hi, i tried to download image_list of datasets
cub200 (https://cloud.tsinghua.edu.cn/f/fa398a321b094a24a347/?dl=1)
stanfordc_cars (https://cloud.tsinghua.edu.cn/f/d95c188cc49c404aba70/?dl=1)
aircraft (https://cloud.tsinghua.edu.cn/f/04356d49d0054092b07e/?dl=1)

but i think they are broken. can you update download url?

**Comment by thucbx99** [comment]
I also found this problem today and it has been fixed in the `tllib `branch
