### ISSUE TITLE
gpus>1 register KeyError when using new datasets

### ISSUE THREAD

**Issue by unknowner22** [thuml/Transfer-Learning-Library#134]
Traceback (most recent call last):
  File "source_only.py", line 189, in <module>
    launch(
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/data/catalog.py", line 51, in get
    f = self[name]
  File "/root/anaconda3/envs/detection/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: '.._.._.._.._DroneVehicle_RGB_day_trainval'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/root/sunyang/Transfer-Learning-Library-dev-tllib/examples/domain_adaptation/object_detection/source_only.py", line 138, in main
    train(model, logger, cfg, args)
  File "/root/sunyang/Transfer-Learning-Library-dev-tllib/examples/domain_adaptation/object_detection/source_only.py", line 74, in train
    train_source_dataset = get_detection_dataset_dicts(args.source)
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/data/build.py", line 240, in get_detection_dataset_dicts
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/data/build.py", line 240, in <listcomp>
    dataset_dicts = [DatasetCatalog.get(dataset_name) for dataset_name in names]
  File "/root/anaconda3/envs/detection/lib/python3.8/site-packages/detectron2/data/catalog.py", line 53, in get
    raise KeyError(
KeyError: "Dataset '.._.._.._.._DroneVehicle_RGB_day_trainval' is not registered! Available datasets are: coco_2014_train, coco_2014_val, coco_2014_minival, coco_2014_minival_100, coco_2014_valminusminival, coco_2017_train, coco_2017_val, coco_2017_test, coco_2017_test-dev, coco_2017_val_100, keypoints_coco_2014_train, keypoints_coco_2014_val, keypoints_coco_2014_minival, keypoints_coco_2014_valminusminival, keypoints_coco_2014_minival_100, keypoints_coco_2017_train, keypoints_coco_2017_val, keypoints_coco_2017_val_100, coco_2017_train_panoptic_separated, coco_2017_train_panoptic_stuffonly, coco_2017_train_panoptic, coco_2017_val_panoptic_separated, coco_2017_val_panoptic_stuffonly, coco_2017_val_panoptic, coco_2017_val_100_panoptic_separated, coco_2017_val_100_panoptic_stuffonly, coco_2017_val_100_panoptic, lvis_v1_train, lvis_v1_val, lvis_v1_test_dev, lvis_v1_test_challenge, lvis_v0.5_train, lvis_v0.5_val, lvis_v0.5_val_rand_100, lvis_v0.5_test, lvis_v0.5_train_cocofied, lvis_v0.5_val_cocofied, cityscapes_fine_instance_seg_train, cityscapes_fine_sem_seg_train, cityscapes_fine_instance_seg_val, cityscapes_fine_sem_seg_val, cityscapes_fine_instance_seg_test, cityscapes_fine_sem_seg_test, cityscapes_fine_panoptic_train, cityscapes_fine_panoptic_val, voc_2007_trainval, voc_2007_train, voc_2007_val, voc_2007_test, voc_2012_trainval, voc_2012_train, voc_2012_val, ade20k_sem_seg_train, ade20k_sem_seg_val"

When I train source_only.py with more than one gpu,the KeyError will appear.
I add classes in \tllib\vision\datasets\object_detection\__init__.py for my own dataset.
How can I solve it, I need help QWQ

**Comment by thucbx99** [comment]
You can try the solution [here](https://github.com/thuml/Transfer-Learning-Library/issues/124)

**Comment by unknowner22** [comment]
> You can try the solution [here](https://github.com/thuml/Transfer-Learning-Library/issues/124)

Thank you！QWQ，this problem is solved perfectly！

I have a new question to ask:
In the D-adapt paper, the loss adv of bbox adaptor uses GIOU loss, but I didn't find its use in the code.
I noticed that the code uses the _**mmd**_ function, the function that calculates the difference value defaults to Smooth L1. Can you point me to the location of the GIOU, thanks a lot!
 I'm taking this article as my graduation project foundation thesis and this place has been very helpful to me.(●'◡'●)

The _**mmd**_ can be find in bbox_adaptation.py  around line 504。
`transfer_loss = mdd(pred_delta_s, pred_delta_s_adv, pred_delta_t, `pred_delta_t_adv)`

**Comment by JunguangJiang** [comment]
Sorry for this 

> > You can try the solution [here](https://github.com/thuml/Transfer-Learning-Library/issues/124)
> 
> Thank you！QWQ，this problem is solved perfectly！
> 
> I have a new question to ask: In the D-adapt paper, the loss adv of bbox adaptor uses GIOU loss, but I didn't find its use in the code. I noticed that the code uses the _**mmd**_ function, the function that calculates the difference value defaults to Smooth L1. Can you point me to the location of the GIOU, thanks a lot! I'm taking this article as my graduation project foundation thesis and this place has been very helpful to me.(●'◡'●)
> 
> The _**mmd**_ can be find in bbox_adaptation.py around line 504。 `transfer_loss = mdd(pred_delta_s, pred_delta_s_adv, pred_delta_t, `pred_delta_t_adv)`

Sorry for the misunderstanding. We used GIoU loss in our old version, now we have changed back to smooth l1 in both the code and the [paper](https://openreview.net/pdf?id=VNqaB1g9393).

**Comment by unknowner22** [comment]
> > I have a new question to ask: In the D-adapt paper, the loss adv of bbox adaptor uses GIOU loss, but I didn't find its use in the code. I noticed that the code uses the _**mmd**_ function, the function that calculates the difference value defaults to Smooth L1. Can you point me to the location of the GIOU, thanks a lot! I'm taking this article as my graduation project foundation thesis and this place has been very helpful to me.(●'◡'●)
> > The _**mmd**_ can be find in bbox_adaptation.py around line 504。 `transfer_loss = mdd(pred_delta_s, pred_delta_s_adv, pred_delta_t, `pred_delta_t_adv)`
> 
> Sorry for the misunderstanding. We used GIoU loss in our old version, now we have changed back to smooth l1 in both the code and the [paper](https://openreview.net/pdf?id=VNqaB1g9393).
> 
> Also, there is no need to spend too much time on this detail, since the core and most effective design in this paper is the decoupling design. The adaptors I design are not necessarily optimal.

Thanks!
Your suggestion is very useful. Because I'm a novice and want to figure out every detail, I'll pay attention to it later. Thank you so much!o(*￣▽￣*)ブ
