### ISSUE TITLE
The code of cyclada seems to be missing the feature adaptation module, could you please add it?

### ISSUE THREAD

**Issue by zhe-juanz** [thuml/Transfer-Learning-Library#135]
Thanks for the excellent work! 
I hava a question，the code of Transfer-Learning-Library/examples/domain_adaptation/semantic_segmentation/**cyclada** seems to be missing the _**feature adaptation**_ module, could you please add it?

**Comment by JunguangJiang** [comment]
[Issue 69](https://github.com/thuml/Transfer-Learning-Library/issues/69) might solve your problem.
