### ISSUE TITLE
'utils' module 

### ISSUE THREAD

**Issue by EvgeniyS99** [thuml/Transfer-Learning-Library#137]
Hello,
I tried to run the code from dann.py, but received the error that module 'utils' has no attributes 'get_dataset_names', 'get_train_transform', 'get_val_transform', etc. Also, I could not find these attributes in 'utils' folder. Could you please help to resolve this problem? Perhaps, I do something wrong. Thank you very much! 
![image](https://user-images.githubusercontent.com/106237959/170234484-462ca4d3-0bac-4c50-b0a6-64f6a7e35343.png)

**Comment by thucbx99** [comment]
Are you running locally or on a server？

**Comment by EvgeniyS99** [comment]
> Are you running locally or on a server？

I am running it in Google Colab using git clone.

**Comment by thucbx99** [comment]
I guess there may be other packages with the same name. You can try to modify the name of `utils.py`, such as `xx_utils.py.`

**Comment by EvgeniyS99** [comment]
> I guess there may be other packages with the same name. You can try to modify the name of `utils.py`, such as `xx_utils.py.`

Thank you for the reply, however, it doesn't work, because 'utils' file doesn't contain those functions which are in code.

**Comment by thucbx99** [comment]
It's a little strange, we have no problem running it locally

**Comment by vanity1129** [comment]
I met the same question but the author's answer really works

**Comment by vanity1129** [comment]
> I met the same question but the author's answer really works



> > I guess there may be other packages with the same name. You can try to modify the name of `utils.py`, such as `xx_utils.py.`
> 
> Thank you for the reply, however, it doesn't work, because 'utils' file doesn't contain those functions which are in code.

I met the same question but the author's answer is really working.
