### ISSUE TITLE
Version string not defined

### ISSUE THREAD

**Issue by billzhonggz** [thuml/Transfer-Learning-Library#138]
**Describe the bug**
When installing on `dev-tllib` branch, the following error occurs and installation aborts.
```python
Traceback (most recent call last):
  File "C:\Users\Junru\source\Transfer-Learning-Library\setup.py", line 9, in <module>
    version = re.search(r'__version__ = \'(.*?)\'', f.read()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**To Reproduce**
1. Clone the repository.
2. Switch to branch `dev-tllib`.
3. Run `python setup.py install`.
4. See error.

**Expected behavior**
No error during install.

**Additional context**
Adding a version string in `tllib/__init__.py` fixes the issue.

**Comment by thucbx99** [comment]
Thank you for pointing out this issue. The `dev-tllib` branch is under development and will be fixed after merging back to the `main` branch. For now, you can directly _git clone_ the project.

**Comment by JunguangJiang** [comment]
Thanks for your advice! 

> **Describe the bug** When installing on `dev-tllib` branch, the following error occurs and installation aborts.
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Users\Junru\source\Transfer-Learning-Library\setup.py", line 9, in <module>
>     version = re.search(r'__version__ = \'(.*?)\'', f.read()).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Clone the repository.
> 2. Switch to branch `dev-tllib`.
> 3. Run `python setup.py install`.
> 4. See error.
> 
> **Expected behavior** No error during install.
> 
> **Additional context** Adding a version string in `tllib/__init__.py` fixes the issue.
