### ISSUE TITLE
Humans 3.6m Dataset creation

### ISSUE THREAD

**Issue by driptaRC** [thuml/Transfer-Learning-Library#142]
It is unclear how to pre-process the Humans 3.6m dataset for RegDA. Can you provide this information?

**Comment by JunguangJiang** [comment]
[Human36M Class](https://github.com/thuml/Transfer-Learning-Library/blob/master/common/vision/datasets/keypoint_detection/human36m.py) has provided the pre-process function

**Comment by driptaRC** [comment]
The preprocess function requires a set of json files that I believe are unavailable to download. Can you provide instructions on how to prepare the dataset as downloaded from the website?

**Comment by JunguangJiang** [comment]
You need to first download these json files from http://vision.imar.ro/human3.6m/description.php. (Login is needed)
After downloading this dataset,  make sure there exist following files  in the `root` directory
 ```
  annotations/
      Human36M_subject11_joint_3d.json
      ...
  images/
```
 Finally, class Human36M will preprocess this dataset automatically.
