### ISSUE TITLE
关于源域和目标域数据的标签问题

### ISSUE THREAD

**Issue by jiusigua** [thuml/Transfer-Learning-Library#144]
你好，我看了代码里关于RegDA模型的训练，想问一下源域和目标域的数据均有关键点信息作为标签是吗？我目前想研究的是源域数据有关键点标签，但是目标域数据没有标签只有图片，然后在源域上训练以后在目标域上进行关键点检测，请问有什么好的建议或者思路吗？谢谢！

**Comment by JunguangJiang** [comment]
RegDA中目标域只有图片，没有标签
