### ISSUE TITLE
关于imagenet-r数据集的格式问题

### ISSUE THREAD

**Issue by fycfycfyc** [thuml/Transfer-Learning-Library#145]
您好，感谢您提供如此好关于迁移学习的开源项目。
我遇到的问题是关于imagenet-r的数据集的格式准备问题，在做image_classfication的域自适应中，我在您提供的链接下载了imagenet-r.tar数据集，并在image_calssfication目录下创建了ImageNetR目录，并将imagenet-r.tar拷贝到了ImageNetR目录下，之后调用解压指令tar -xvf imagenet-r.tar 解压了iamgenet-r.tar压缩包，最后调用UDA_VISIBLE_DEVICES=0 python dann.py data/ImageNetR -d ImageNetR -s IN -t INR -a resnet50 --epochs 30 -i 2500 -p 500 --seed 0 --log logs/dann/ImageNet_IN2INR启动脚本。但是程序报错，报错信息如下：
FileNotFoundError: [Errno 2] No such file or directory: 'data/ImageNetR/train/n09835506/n09835506_14973.JPEG'
初步判断就是imagenet-r数据集并没有按照规定的格式进行准备，但是该错误意思是该数据集有train和val的划分，但是我解压imagenet-r.tar发现并没有划分train和val，看您的说明文档让在imagenet-r.py查看数据集准备的格式，但是我在该文件中并没有看到相关的代码，所以想请教您一下这个数据集的准备工作具体怎么做呢？
非常期待您的回复，我是在linux系统上进行测试，不过感觉这个bug和系统关系也不大。

**Comment by fycfycfyc** [comment]
感谢您的回复，但是我运行了该命令，报错了图片路径找不到，应该就是imagenet-r的数据集没有正确解压，在第一次提问中也说明了这个问题，所以想请问一下您是如何组织这个imagenet-r数据集的？那个参考脚本其他指令都是运行过程中会自动将数据集下载并合理组织目录，但是imagenet-r是手动下载，并没有明确如何组织目录。
期待您的回复！



---原始邮件---
发件人: "Jiang ***@***.***&gt;
发送时间: 2022年6月14日(周二) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuml/Transfer-Learning-Library] 关于imagenet-r数据集的格式问题 (Issue #145)




 
imagenet-r一般只用来评估，imagenet作为训练集
 参考脚本给出了使用例子
 CUDA_VISIBLE_DEVICES=0 python dann.py data/ImageNetR -d ImageNetR -s IN -t INR -a resnet50 --epochs 30 -i 2500 -p 500 --seed 0 --log logs/dann/ImageNet_IN2INR

**Comment by JunguangJiang** [comment]
[imagenet-r的文档](https://github.com/thuml/Transfer-Learning-Library/blob/dev-tllib/tllib/vision/datasets/imagenet_r.py)里有写路径格式

**Comment by fycfycfyc** [comment]
谢谢您的回复~
&nbsp; &nbsp; &nbsp; 关于数据集我还有一个问题就是您在imagenet_sketch.py描述image_sketch这个数据集准备工作的时候谈到了需要在目录下准备“metabin” of ImageNet-1k这个文件，但是我在Imagenet官网上并没有找到该文件的相关信息，请问这个文件您是从哪里获取的呀？可否给出一个获取链接或者途径？
期待您的回复~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Transfer-Learning-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月15日(星期三) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Transfer-Learning-Library] 关于imagenet-r数据集的格式问题 (Issue #145)





 
imagenet-r的文档里有写路径格式

**Comment by JunguangJiang** [comment]
ImageNet本身就提供了这个文件，可以看一下 https://github.com/pytorch/vision/blob/main/torchvision/datasets/imagenet.py

**Comment by fycfycfyc** [comment]
好的，谢谢您的回复～



---原始邮件---
发件人: "Jiang ***@***.***&gt;
发送时间: 2022年6月17日(周五) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thuml/Transfer-Learning-Library] 关于imagenet-r数据集的格式问题 (Issue #145)




 
ImageNet本身就提供了这个文件，可以看一下 https://github.com/pytorch/vision/blob/main/torchvision/datasets/imagenet.py
