### ISSUE TITLE
About the high accuracy of DANN

### ISSUE THREAD

**Issue by cherryappleyyyyyy** [thuml/Transfer-Learning-Library#147]
The accuracy rate of DANN published in this paper in Office31 data set is 82.2%, but the actual result I get by running this DANN code is much higher than 82.2%. Is this normal? It was also higher on the OfficeHome data set than published in the paper.

**Comment by thucbx99** [comment]
We report both the results of the original paper and the reproduced results. For the image classification task, the results are [here](https://github.com/thuml/Transfer-Learning-Library/tree/dev-tllib/examples/domain_adaptation/image_classification). For DANN, our implementation does achieve better results on both the Office31 and OfficeHome datasets.
