### ISSUE TITLE
A data leakage problem in ADDA method training phase

### ISSUE THREAD

**Issue by Aknifejackzhmolong** [thuml/Transfer-Learning-Library#153]
**Describe the bug**
It look like a data leakage problem in files [adda.py](https://github.com/thuml/Transfer-Learning-Library/blob/09d0eb81b009ed72c620091b9265ea49412b9fcd/examples/domain_adaptation/image_classification/adda.py) & [utils.py](https://github.com/thuml/Transfer-Learning-Library/blob/09d0eb81b009ed72c620091b9265ea49412b9fcd/examples/domain_adaptation/image_classification/utils.py) because the val_loader and test_loader is equal some time.

In training phase, the val_loader are used in calculating acc and to save best model, but in test phase the test_loader which are used in calculating accuray performance of model is the same as val_loader.

**Expect behavor**
I want to run a unsupervised domain adaptation program. 

Please kindly advise.

**Screenshots**
adda.py
![image](https://user-images.githubusercontent.com/23431216/182027249-69fb0818-17d2-4c4a-a10f-7413e7cfae95.png)
![image](https://user-images.githubusercontent.com/23431216/182027233-c920e288-b3fb-44df-9ba0-4474d54d0d71.png)

utils.py
![image](https://user-images.githubusercontent.com/23431216/182027283-46c43f46-4ec6-43eb-a70f-892a6157b4fe.png)

**Comment by thucbx99** [comment]
Hope [issue15](https://github.com/thuml/Transfer-Learning-Library/issues/15), [issue28](https://github.com/thuml/Transfer-Learning-Library/issues/28), [issue47](https://github.com/thuml/Transfer-Learning-Library/issues/47) and [issue105](https://github.com/thuml/Transfer-Learning-Library/issues/105) could answer your question.
