### ISSUE TITLE
Help on Trainning with custom dataset

### ISSUE THREAD

**Issue by Mininggamer** [thuml/Transfer-Learning-Library#155]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thucbx99** [comment]
In general, you can replace the part about the dataset in the training script with a custom one. Under which task do you want to use the custom dataset?

**Comment by coder-chica97** [comment]
@thucbx99 , what shell command do I use for me to run adda on my own dataset?
`adda.py data/myowndataset ________ `
Thank you.

**Comment by coder-chica97** [comment]
@Mininggamer sorry to bother you! But did you succeed with the custom dataset?

**Comment by thucbx99** [comment]
> @thucbx99 , what shell command do I use for me to run adda on my own dataset? `adda.py data/myowndataset ________ ` Thank you.

Should be the name of the python class. For example, we define the class `Office31` [here](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/office31.py). The corresponding command is `-d Office31`.
