### ISSUE TITLE
您好，关于Human3.6M数据集的使用

### ISSUE THREAD

**Issue by davidpengiupui** [thuml/Transfer-Learning-Library#157]
**Is your feature request related to a problem? Please describe.**
关于RegDA的部分，human3.6m 数据集的使用，#142 中的链接已经失效

**Describe the solution you'd like**
请问能否提供预处理的代码？因为Human3.6m这个数据集比较复杂，包含多个压缩包。鄙人不清楚S1 S5这些文件夹应该存放哪些东西。另外，官方数据集提供的annotation是mat格式，然而这边代码里显示的是Human36M_subject11_joint_3d.json，想请教一下是如何生成的？

**Describe alternatives you've considered**
如果您愿意分享一些资料的话，我的邮箱是qupeng@iu.edu

**Additional context**
万分感谢，打扰了！

**Comment by thucbx99** [comment]
`Human3.6m`下载下来应该有`json`格式，我们也上传到了[云盘](https://cloud.tsinghua.edu.cn/f/7b588ad20400464fb07a/?dl=1)。数据的预处理可以参考这里的[代码](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/keypoint_detection/human36m.py)。

**Comment by davidpengiupui** [comment]
感谢回复！
