### ISSUE TITLE
"Fail to download image_list.zip from url link ______ " Please check you internet connection. Simply trying again may be fine.

### ISSUE THREAD

**Issue by chiragpr** [thuml/Transfer-Learning-Library#159]
I try to run the same exact code, but I get this on all datasets.

**Comment by thucbx99** [comment]
I just tried to download the imagelist corresponding to _Office31_ and _OfficeHome_ and it was successful. Maybe there were some problems with Tsinghua cloud when you tried it.

**Comment by chiragpr** [comment]
Still the same issue... Have you run it on a windows or Linux?

**Comment by thucbx99** [comment]
I have tried both on linux and windows and both work. You can try to download directly from the link, such as `line 39` in this [file](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/office31.py).
