### ISSUE TITLE
目标检测域适应中的cycle gan，只有训练程序，没有验证程序呢？？？？？

### ISSUE THREAD

**Issue by shishi-jie** [thuml/Transfer-Learning-Library#160]

**Comment by shishi-jie** [comment]
大佬，如何得到验证指标呢？？

**Comment by thucbx99** [comment]
我们使用`CycleGAN`的目的是为了帮助后续的迁移学习，比如在`domain adaptation`中，我们会使用`CycleGAN`将`source domain`的样本转换为风格更接近于`target domain`的样本来减少`domain gap`。因此我们不直接评估`GAN`的好坏，而是评估其生成的图片在`target domain`训练的效果。

**Comment by thucbx99** [comment]
我们在[脚本文件中](https://github.com/thuml/Transfer-Learning-Library/blob/master/examples/domain_adaptation/object_detection/cycle_gan.sh)提供了这样的例子，比如`1-17`行。

**Comment by shishi-jie** [comment]
好的好的，谢谢百忙之中抽空解答哈哈

**Comment by thucbx99** [comment]
不客气哈哈
