### ISSUE TITLE
Missing requirements to be installed in `setup.py`

### ISSUE THREAD

**Issue by phamour** [thuml/Transfer-Learning-Library#161]
**Describe the bug**
In `setup.py`, requirements to be installed are hardcoded and inconsistent with `requirements.txt`.

**To Reproduce**
1. Under a clean env (say a new virtual env), install tllib from source through `pip install .`
2. Call `python -c "from tllib.ranking import log_maximum_evidence"`
3. See error "ModuleNotFoundError: No module named 'numba'"

**Expected behavior**
No import error after a clean installation.

**Screenshots**
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/4461484/187678124-f7a76b89-c77c-40f1-b7d3-d95032f0a5f0.png">

**Comment by thucbx99** [comment]
Thanks for pointing this out and providing a neat solution！
