### ISSUE TITLE
Failed to import mmdetection

### ISSUE THREAD

**Issue by SeucheAchat9115** [thuml/Transfer-Learning-Library#163]
When i try to run source_only.py I get the error message "No module named 'tlllib.vision.models.object_detection.backbone.mmdetection'"

If I try to import "tlllib.vision.models.object_detection" it seems that the error is in the file backbone/vgg.py in "from .mmdetection.vgg import VGG.
Any clue how I can fix this?

**Comment by thucbx99** [comment]
I just tried it and found no problem. Can you find this file in the corresponding directory?

<img width="749" alt="image" src="https://user-images.githubusercontent.com/57670068/188475636-fc0d29ad-0918-4b5b-aa51-4c9be3eb3525.png">

**Comment by SeucheAchat9115** [comment]
The problem was I installed tllib using pip, but this somehow did not work. Therefore I had to uninstall it and load tllib from the source files directly.

**Comment by thucbx99** [comment]
Temporarily tllib does not support installing via pip yet, we are planning to support it recently.

**Comment by thucbx99** [comment]
We have supported installing tllib via pip using the following command.

`pip install -i https://test.pypi.org/simple/ tllib==0.4`

**Comment by mahilaMoghadami** [comment]
I have still this problem and get the error, how can I solve it? 
error:
ModuleNotFoundError: No module named 'tllib.vision.models.object_detection.backbone.mmdetection'

I tried to  installed tllib with both pip and source file, but it didnt work for me.
appreciate your help.

**Comment by mahilaMoghadami** [comment]
> The problem was I installed tllib using pip, but this somehow did not work. Therefore I had to uninstall it and load tllib from the source files directly.

hello
could you please tell me how did you do that?
thank you.

**Comment by SeucheAchat9115** [comment]
I cloned the tlllib from github and then it worked. No need to pip install.
