### ISSUE TITLE
请问 synthia中，synthia_mapped_to_cityscapes这个文件在哪里能找到

### ISSUE THREAD

**Issue by yuheyuan** [thuml/Transfer-Learning-Library#165]
```txt
data/synthia
├── RGB
├── synthia_mapped_to_cityscapes
└── ...
```

我在那个官网上下载了
SYNTHIA-RAND-CITYSCAPES (CVPR16)
但里面没有这个文件，我之前跑的网络用的是上面这个数据及，但这个我看 UDA里面 synthia里面 readme有要这个文件

**Comment by thucbx99** [comment]
这个文件应该是下载下来就有的，我们刚刚上传到了云盘，可以通过下面的链接下载
https://cloud.tsinghua.edu.cn/f/15aa5901c7104108856a/?dl=1

**Comment by kiranchari** [comment]
@thucbx99 I downloaded the folder you shared but get an error. Is there are a more updated version?

`FileNotFoundError: [Errno 2] No such file or directory: '/datasets/synthia/synthia_mapped_to_cityscapes/0005012.png'`

**Comment by kiranchari** [comment]
@thucbx99 May I also know why results for only 13 classes are listed for Synthia -> Cityscapes at this link?: https://github.com/thuml/Transfer-Learning-Library/tree/master/examples/domain_adaptation/semantic_segmentation

AFAIK, there are 16 common classes between Synthia and Cityscapes. 

Thanks.

**Comment by kiranchari** [comment]
@yuheyuan did you manage to solve this problem with the download link provided?
