### ISSUE TITLE
在MCD code内，训练代码，数据载入好像有点Bug

### ISSUE THREAD

**Issue by Sevenddd** [thuml/Transfer-Learning-Library#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thucbx99** [comment]
具体报错是什么呢，我直接运行是没有问题的

**Comment by Sevenddd** [comment]
您好。
我看了一下，你先拼接了源域和目标域，变成x，


后面x再拆分变成 y1， y2，&nbsp; 后面拿源域的标签分别和y1，y2计算，感觉这里有点问题。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Transfer-Learning-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月26日(星期一) 下午4:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Transfer-Learning-Library] 在MCD code内，训练代码，数据载入好像有点Bug (Issue #168)





 
具体报错是什么呢，我直接运行是没有问题的

**Comment by thucbx99** [comment]
可以再具体一点吗，听起来你的问题并不是MCD的代码运行起来会报错，而是这里的逻辑有一些问题吗？
