### ISSUE TITLE
OfficeCaltech下载数据集报错

### ISSUE THREAD

**Issue by siriuspei** [thuml/Transfer-Learning-Library#17]
File "/home/lab/workspace/Transfer/dalib/vision/datasets/officecaltech.py", line 59, in __init__
    self.classes = OfficeCaltech.classes
AttributeError: type object 'OfficeCaltech' has no attribute 'classes'

**Comment by JunguangJiang** [comment]
Thanks for your comments. "OfficeCaltech.classes" should be "OfficeCaltech.CLASSES". We have fixed it now.
