### ISSUE TITLE
目标域数据json文件的真值

### ISSUE THREAD

**Issue by MissingJade** [thuml/Transfer-Learning-Library#171]
想请问一下作者在用目标域数据训练时，生成的目标域数据proposal文件中含有真值信息，然而域自适应是在没有目标域真值的情况下使用的方法，那么请问当不提供目标域数据的真值时，还有可以用目标域数据训练吗

**Comment by thucbx99** [comment]
你指的是DA Detection这里吗，proposal中包含真值只是方便我们分析，实际上并没有用他们训练

**Comment by MissingJade** [comment]
那请问您d_adapt.py文件多gpu能运行成功吗，我这边无法多gpu运行

**Comment by thucbx99** [comment]
具体的报错是什么呀，之前也有类似的[issue](https://github.com/thuml/Transfer-Learning-Library/issues/134)。最新的版本已经修复好了，你可以看一下你本地的代码是否也这样修改过

**Comment by MissingJade** [comment]
我下次记录下来，怎么修复的呀

**Comment by MissingJade** [comment]
我在运行d_adapt.sh时报错的，我看了下源代码好像没有实现多gpu这一块，最直接的错误就是bg.json和fg.json文件保存的次数和设置的gpu数目一致，应该是每个子进程里都做了写入json文件这个操作

**Comment by JunguangJiang** [comment]
源代码没有实现多gpu，原因是大部分的DA训练方式在多卡时可能会出现性能下降。所以一种解决办法是，将DA训练的部分用单卡训练处理，检测训练部分的代码（伪标签训练不涉及DA）用多卡训练

**Comment by MissingJade** [comment]
好的，谢谢作者，我自己实现了一份多gpu运行的代码，试试效果如何

**Comment by thucbx99** [comment]
理论上检测这一步是没有影响的，DA分类分类的这一步可能是由于BatchNorm等，可能需要注意一下使用syncBN之类的操作
