### ISSUE TITLE
ADDA Architecture

### ISSUE THREAD

**Issue by evablanco** [thuml/Transfer-Learning-Library#172]
Hi,

I am trying to modify ADDA from your code. In the original paper, there seems to be 2 CNNs in the second training phase, one to process the examples of the target set and another with the frozen weights to process the examples of the source set. In this way, the CNN of the target set is 'adjusted' to that of the source set depending on the output of the domain discriminator.

However, when reviewing the code it seems that only a single CNN is used, adjusting in a first phase the model (extractor+classifier) and in a second phase only the domain discriminator. My questions is how then the training of both phases is reproduced in the library. Thank you very much!

Best regards,

Eva

**Comment by thucbx99** [comment]
Hi,

Indeed, the current implementation is different from the original ADDA. 

- In a previous [version](https://github.com/thuml/Transfer-Learning-Library/commit/b82c83cabf470d665f66d3440acbad8660b77b87#diff-28923802ec1f068973e425081f70f5aee4bcde3d101e7645f4fb82c788935bd8), I implement ADDA with gradient reverse layer. 
- You can also refer to this [commit](https://github.com/thuml/Transfer-Learning-Library/commit/4223a4f84092efd4c35f3c5c71d675ba37c6139d#diff-d6c323d57ec388cfc342015e00ed11b7238fc033cc9661e79af01ae9f539d86c) which implements improved adversarial loss as proposed in ADDA, similar to GAN.
- However, I do not observe better performance compared to DANN. As a result, I only keep the current version. Maybe you can achieve better performance through careful tuning.
