### ISSUE TITLE
Code for Mean Embedding Test

### ISSUE THREAD

**Issue by KEVIN666666666** [thuml/Transfer-Learning-Library#174]
Hi there,

In the paper "Transferable Representation Learning with Deep Adaptation Networks",

There are 2 Two-Sample Test Statistics, MK-MMD and Mean Embedding Test (ME), I can find the code for MK-MMD but can't find any clue for ME, is there any code for ME or will the code for ME be avaliable?

**Comment by thucbx99** [comment]
Hi, 

We do notice this is missing in our library. Yet currently we are too busy to support it. Maybe you can refer to recent works on _DA Theory_ or _Decision Making Theory_ to see if they implement the code.
