### ISSUE TITLE
Question about the PCK threshold setting about the evaluation of keypoint detection

### ISSUE THREAD

**Issue by delaprada** [thuml/Transfer-Learning-Library#178]
Hello!

I read the paper of "Regressive Domain Adaptation for Unsupervised Keypoint Detection" today and found that the PCK threshold setting is described in the paper as below:
```
An estimation is considered correct if its distance from the ground truth is less than a fraction α = 0.05 of the image size.
```

But when I read the source code:
https://github.com/thuml/Transfer-Learning-Library/blob/b731e85e8e9eb79315da54a6fbe3c3efbf810adf/examples/domain_adaptation/keypoint_detection/erm.py#L247
I found that the accuracy function strictly set the threshold to 0.5.

So which one should I choose when I do my experiment would be better? A fraction α = 0.05 of the image size or 0.5?

Thank you.

**Comment by JunguangJiang** [comment]
The evaluation code is adapted from `https://github.com/microsoft/human-pose-estimation.pytorch/blob/18f1d0fa5b5db7fe08de640610f3fdbdbed8fb2f/lib/core/evaluate.py`.

**Comment by delaprada** [comment]
Thank you for your kindly explanation! I understand what you mean. @JunguangJiang
