### ISSUE TITLE
Importing wrong DomainAdversarialLoss

### ISSUE THREAD

**Issue by kiranchari** [thuml/Transfer-Learning-Library#179]
**Describe the bug**

The code imports tllib.alignment.**dann**.DomainAdversarialLoss instead of tllib.alignment.**adda**.DomainAdversarialLoss in adda.py (see https://github.com/thuml/Transfer-Learning-Library/blob/master/examples/domain_adaptation/image_classification/adda.py#L25)

Is this correct?

**Comment by thucbx99** [comment]
Yes, and this is because we implemented several modified versions of ADDA but only kept the better performing one. You can refer to [issue172](https://github.com/thuml/Transfer-Learning-Library/issues/172) for details.

**Comment by kiranchari** [comment]
ok thanks
