### ISSUE TITLE
Can't download office-caltech dataset by dalib!!!

### ISSUE THREAD

**Issue by weiyikang** [thuml/Transfer-Learning-Library#18]
environment:
1. Unbuntu;
2. pytorch==1.5.1;
3. install dalib by "pip install dalib", dalib==0.2

There be some errors by using dalib to download office-caltech dataset as follows:

![image](https://user-images.githubusercontent.com/15953968/101302324-44699a80-3876-11eb-8880-3986ee354372.png)

How to solve the problem? I just want to use "pip install dalib" to install the dalib.

**Comment by microhhh** [comment]
For flexible use and modification, please git clone the library.  Pip installation is no longer recommended.
