### ISSUE TITLE
A bug in rsd.py

### ISSUE THREAD

**Issue by aragakiyui611** [thuml/Transfer-Learning-Library#180]
https://github.com/thuml/Transfer-Learning-Library/blob/7f0bc105f1d8adedf6e8d281a29ced8814d96065/examples/domain_adaptation/image_regression/rsd.py#L87

https://github.com/thuml/Transfer-Learning-Library/blob/7f0bc105f1d8adedf6e8d281a29ced8814d96065/examples/domain_adaptation/image_regression/rsd.py#L91

This two line, the output dim doesn't match.  Should change to ` regressor = Regressor(backbone=backbone, num_factors=num_factors, bottleneck=bottleneck, bottleneck_dim=256).to(device)` or something else.

**Comment by thucbx99** [comment]
Thanks for pointing this out and we have fix it
