### ISSUE TITLE
sim10k数据集 repro_image_sets.tgz下载不了

### ISSUE THREAD

**Issue by sysuzgg** [thuml/Transfer-Learning-Library#185]
你好，多次尝试不能下载 repro_image_sets.tgz，这个文件不大，可否给我发一下呢？邮箱1213268188@qq.com

**Comment by thucbx99** [comment]
我创建了一个云盘链接，可以直接下载

https://cloud.tsinghua.edu.cn/f/ebec22c96696448b9b0f/?dl=1
