### ISSUE TITLE
How to train on custom datasets?

### ISSUE THREAD

**Issue by lualualualu** [thuml/Transfer-Learning-Library#188]

**Comment by thucbx99** [comment]
You can refer to the implementation of datasets in our library. For example, we define [ImageList](https://github.com/thuml/Transfer-Learning-Library/blob/c4b0dfd1d0493f70958b715de5d7b12383954028/tllib/vision/datasets/imagelist.py#L15) as a base class on image classification task. Then we inherit ImageList class to implement specific datasets, such as [Office31](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/office31.py).

The most straightforward way to train on custom datasets is to mimic our implementation. However, this can be flexible
, such as the implementation of [Food101](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/food101.py). And you may need to modify the data loading code correspondingly.
