### ISSUE TITLE
after install from github, it report indentation error when import tllib

### ISSUE THREAD

**Issue by zhouyu5** [thuml/Transfer-Learning-Library#190]
**Describe the bug**
after install from github, it report indentation error when import tllib

**To Reproduce**
1. install from github
```shell
git clone https://github.com/thuml/Transfer-Learning-Library.git /tmp/tllib && \
    cd /tmp/tllib/ && \
    pip install -r requirements.txt && \
    python setup.py install && \
    rm -rf /tmp/tllib
```
2. then import tllib, 
```python
import tllib
```
3. then error occurs
```
File /****/python3.9/site-packages/tllib-0.4-py3.9.egg/tllib/ranking/hscore.py:69
    f = features.astype('float64')
                                  ^
IndentationError: unindent does not match any outer indentation level
```

**Expected behavior**
No error occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/12825276/210733843-a624df5b-23f0-416c-895b-4d59463ddfe0.png)

**Comment by thucbx99** [comment]
We have fixed this bug
