### ISSUE TITLE
val_loader和test_loader相同

### ISSUE THREAD

**Issue by hacker-han** [thuml/Transfer-Learning-Library#191]
你好，exampels文件夹下domain_adaptation下的image_classification里面那些方法，用到的val_loader和test_loader从代码上看是相同的，验证集和测试集相同这一点多少有点问题吧

**Comment by hacker-han** [comment]
![image](https://user-images.githubusercontent.com/52616908/210976500-7384e479-826b-49c1-a401-d3a8d2ce2ae0.png)
从代码上看这大多数的情况下会执行这个else里的代码

**Comment by thucbx99** [comment]
这是Domain Adaptation领域中的一个历史问题，可以参考我们之前的解释如https://github.com/thuml/Transfer-Learning-Library/issues/15, https://github.com/thuml/Transfer-Learning-Library/issues/28, https://github.com/thuml/Transfer-Learning-Library/issues/47, https://github.com/thuml/Transfer-Learning-Library/issues/105, https://github.com/thuml/Transfer-Learning-Library/issues/153
