### ISSUE TITLE
error while running train script

### ISSUE THREAD

**Issue by 1a-borovik1** [thuml/Transfer-Learning-Library#194]
I set up env with: 
python setup.py install
pip install -r requirements.txt

and then i try to launch training with next command: 
python3 ./examples/domain_adaptation/image_regression/dann.py ImageRegression -d ImageRegression -s A -t W -a resnet50  --epochs 20

and i get: 
Traceback (most recent call last):
  File "./examples/domain_adaptation/image_regression/dann.py", line 313, in <module>
    main(args)
  File "./examples/domain_adaptation/image_regression/dann.py", line 66, in main
    train_source_dataset = dataset(
TypeError: __init__() got an unexpected keyword argument 'task'

**Comment by thucbx99** [comment]
This is because ImageRegression is the superclass. Usually we inherit from it and implement the subclass, such as [DSprites](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/vision/datasets/regression/dsprites.py). I think maybe you want to train on your custom dataset?
