### ISSUE TITLE
作者您好，关于RegDA使用Human3.6M数据标签问题

### ISSUE THREAD

**Issue by HycFacny** [thuml/Transfer-Learning-Library#198]
作者您好，我是目前开始着手做2D HPE 相关课题的学生，想对RegDA进行复现。
想问一下库中对于Humain3.6M 标签的格式问题。
代码位置在Transfer-Learning-Library/tree/master/tllib/vision/datasets/keypoint_detection/human3.6m.py。
```
.. note:: You need to download Human36M manually.
        Ensure that there exist following files in the `root` directory before you using this class.
        ::
            annotations/
                Human36M_subject11_joint_3d.json
                ...
            images/
```
我自行下载的数据集中并不包含此类json文件，想知道他们的格式如何，或者是否存在数据集官方的pkl cdf等格式转json格式的相关脚本。
非常感谢！！

**Comment by thucbx99** [comment]
可以参考这里的回答 https://github.com/thuml/Transfer-Learning-Library/issues/157

**Comment by HycFacny** [comment]
> 可以参考这里的回答 #157

云盘失效，可否单独分享一下json文件呢，我下载的这一份数据集里没有包含json文件。

**Comment by thucbx99** [comment]
抱歉，我们的云盘最近好像不太稳定，已经重新整理到了[这里](https://cloud.tsinghua.edu.cn/f/97d1a4ee9d574790a1e8/?dl=1)。因为我本人不太懂这个数据集的结构，还是上传了全部的数据，防止有遗漏

**Comment by linqiuxia-lynn** [comment]
> 抱歉，我们的云盘最近好像不太稳定，已经重新整理到了[这里](https://cloud.tsinghua.edu.cn/f/97d1a4ee9d574790a1e8/?dl=1)。因为我本人不太懂这个数据集的结构，还是上传了全部的数据，防止有遗漏

Hi @thucbx99, I'm prompted that there is a **data error in keypoint2d.json** when unzipping the new file, which results in unsuccessful extraction. Could you please help me solve this issue? Appreciate any feedback from you!

**Comment by thucbx99** [comment]
@linqiuxia-lynn We have uploaded this file [here](https://cloud.tsinghua.edu.cn/f/9d2fc4704cae4d3caea8/?dl=1).

**Comment by linqiuxia-lynn** [comment]
Thanks so much for your reply!
