### ISSUE TITLE
tllib/vision/datasets/digits.py中的数据集URL失效

### ISSUE THREAD

**Issue by 781226451** [thuml/Transfer-Learning-Library#199]
作者你好，我在运行DANN.py进行SVHN->MNIST的迁移学习过程中发现SVHNRGB这个dataset无法下载数据。经过分析发现tllib/vision/datasets/digits.py中涉及到的MNIST,USPS,SVHN三个类中download url(清华网盘)均已失效。请问这些数据是否可以使用torchvision库中的对应数据代替？

**Comment by thucbx99** [comment]
我们已经更新了这几个链接
