### ISSUE TITLE
t-SNE

### ISSUE THREAD

**Issue by Zhengzkang** [thuml/Transfer-Learning-Library#200]
帅哥，你好，能不能提供一下t-SNE可视化代码，最近一直在搞这方面实验，一直失败，我将不胜感激，感激涕零

**Comment by thucbx99** [comment]
可以参考我们的[代码](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/utils/analysis/tsne.py)，其实就是调用sklearn的TSNE，相关的教程很多
