### ISSUE TITLE
`pip install tllib`

### ISSUE THREAD

**Issue by zhouyu5** [thuml/Transfer-Learning-Library#207]
**Is your feature request related to a problem? Please describe.**
provide a formal way to install tllib

**Describe the solution you'd like**
`pip install tllib`

**Additional context**
currently install through `pip install -i https://test.pypi.org/simple/ tllib==0.4`, we cannot add dependency in requirement.txt since it try to search package in pypi.org

**Comment by thucbx99** [comment]
We have also been considering supporting the use of pip to install tllib. Recently, we will check the code and support it after we obtain a more stable version.

**Comment by zhouyu5** [comment]
> We have also been considering supporting the use of pip to install tllib. Recently, we will check the code and support it after we obtain a more stable version.

@thucbx99 Thanks for replying. This repo is very helpful. Thanks for your great work. When can we found it in official pypi source?

**Comment by zhouyu5** [comment]
If you are busy, I can offer this help. Please tell me if you want me to upload it to pypi. Thanks~
