### ISSUE TITLE
SOS from a newbie

### ISSUE THREAD

**Issue by silence-user-wu** [thuml/Transfer-Learning-Library#21]
Sorry for bothering you in thid holiday. I`m a postgraduate freshmen of medical statistics. My master's supervisor wish I can find more than one method of machine learning to predict prediction (for example death rate) using structured data(for example Red blood cell count). And he still want me to use transfer learning for  increasing the efficiency and accuracy. 

If you have time, please recommend some good models to me. Even better if you can introduce some open source projects in github.

Thanks a million for your help

**Comment by microhhh** [comment]
Sorry we don’t know about medical statistics, you can read more academic materials such as papers.
