### ISSUE TITLE
你好，我在运行d_adapt.py时遇到了一个问题，KeyError: 'TLGeneralizedRCNN'

### ISSUE THREAD

**Issue by tiamjiakun** [thuml/Transfer-Learning-Library#211]
错误在model = models.__dict__[cfg.MODEL.META_ARCHITECTURE](cfg, finetune=args.finetune)这一行出现。
出现这个错误后，我将faster_rcnn_R_101_C4_voc.yaml中的META_ARCHITECTURE值由 TLGeneralizedRCNN 改为了DecoupledGeneralizedRCNN，然后程序可以运行了，请问我这样会产生不利的影响吗？

**Comment by 985767019** [comment]
> 错误在model = models.**dict**[cfg.MODEL.META_ARCHITECTURE](cfg, finetune=args.finetune)这一行出现。 出现这个错误后，我将faster_rcnn_R_101_C4_voc.yaml中的META_ARCHITECTURE值由 TLGeneralizedRCNN 改为了DecoupledGeneralizedRCNN，然后程序可以运行了，请问我这样会产生不利的影响吗？

你好，我改了好像还是跑不了，能教一下吗？哥们

**Comment by tiamjiakun** [comment]
> > 错误在 model = models. **dict** [cfg.MODEL.META_ARCHITECTURE](cfg,finetune=args.finetune) 这行出现。出现这个错误后，我将faster_rcnn_R_101_C4_voc.yaml中的META_ARCHITECTURE值由 TLGeneralizedRCNN 改为了De CoupledGeneralizedRCNN，然后程序就可以运行了，请问我这样会产生不利的影响吗？
> 
> 你好，我改了愿望还是跑不了，能教一下吗？哥们
我记得不是用faster_rcnn_R_101_C4_voc.yaml，而是用更下一级的文件夹里面的YAML文件，也不用调整META_ARCHITECTURE的值，直接运行就行

**Comment by 985767019** [comment]
谢谢，之前那个配置文件我用的是你说的那个，可能是包不兼容，他当时报的错是这样的：KeyError: 'DecoupledGeneralizedRCNN'






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月18日(星期三) 晚上8:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Transfer-Learning-Library] 你好，我在运行d_adapt.py时遇到了一个问题，KeyError: &#39;TLGeneralizedRCNN&#39; (Issue #211)





   
错误在 model = models. dict cfg.MODEL.META_ARCHITECTURE 这行出现。出现这个错误后，我将faster_rcnn_R_101_C4_voc.yaml中的META_ARCHITECTURE值由 TLGeneralizedRCNN 改为了De CoupledGeneralizedRCNN，然后程序就可以运行了，请问我这样会产生不利的影响吗？
  
你好，我改了愿望还是跑不了，能教一下吗？哥们
 我记得不是用faster_rcnn_R_101_C4_voc.yaml，而是用更下一级的文件夹里面的YAML文件，也不用调整META_ARCHITECTURE的值，直接运行就行
