### ISSUE TITLE
关于source_only.py和cityscapes.yaml中学习率的疑问

### ISSUE THREAD

**Issue by murenma05** [thuml/Transfer-Learning-Library#214]
作者大神您好，在查看source_only.py代码的时候我看到训练过程使用了Warmup策略，初始学习率为0.005，后续100轮次每轮增加0.001，请问我理解的正确吗？100轮次后的学习率变化是怎样的呢？还希望大神可以指点一下，谢谢！

用到的命令如下：
```
CUDA_VISIBLE_DEVICES=0 python source_only.py \
  --config-file config/faster_rcnn_R_101_C4_cityscapes.yaml \
  -s   Cityscapes datasets/cityscapes_in_voc \
  -t Cityscapes datasets/cityscapes_in_voc  \
  --test CityscapesTest datasets/cityscapes_in_voc --finetune \
  OUTPUT_DIR logs/source_only/faster_rcnn_R_101_C4/CS2CS 
```

**Comment by thucbx99** [comment]
这里我们直接使用detectron2的实现，你可以参考下面的链接，warmup之后就是标准的StepLr，即每隔若干epoch减少为之前的几分之一
https://github.com/facebookresearch/detectron2/tree/main/detectron2/solver
