### ISSUE TITLE
关于自定义网络问题

### ISSUE THREAD

**Issue by JiaQi1996** [thuml/Transfer-Learning-Library#215]
作者您好，非常感谢您能够构建TLlib。在使用TLlib的过程中，我想要自定义一个多分枝网络（类似于BBN或使用多个分类器），请问TLlib能否支持自定义网络。

**Comment by thucbx99** [comment]
可以的，你只需要重写[Classifier](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/modules/classifier.py#LL12C11-L12C11)类即可，我们目前实现的方法中也有一些需要多分枝网络，比如[MDD](https://github.com/thuml/Transfer-Learning-Library/blob/master/tllib/alignment/mdd.py)中实现的有main head和adversarial head的module，你可以参考一下
