### ISSUE TITLE
Data processing of SURREAL and H3D

### ISSUE THREAD

**Issue by hnuzhy** [thuml/Transfer-Learning-Library#224]
Hello, I want to ask some data processing details of the RegDA algorithm.
https://github.com/thuml/Transfer-Learning-Library/tree/master/examples/domain_adaptation/keypoint_detection

As shown in the README, datasets SURREAL and Hand-3d-Studio can be downloaded automaticly with processd, sampled and cropped versions which are provided by you.

* processd SURREAL dataset: https://github.com/thuml/Transfer-Learning-Library/blob/d950c3115557423cd5dcec3fdeee2c3ffb2cae5a/tllib/vision/datasets/keypoint_detection/surreal.py
* processd Hand-3d-Studio dataset: https://github.com/thuml/Transfer-Learning-Library/blob/d950c3115557423cd5dcec3fdeee2c3ffb2cae5a/tllib/vision/datasets/keypoint_detection/hand_3d_studio.py

Now, I want to get the corresponding original image and labels of each processd sample. So, could you please release the cropping scripts for SURREAL and Hand-3d-Studio datasets?

**Comment by thucbx99** [comment]
The original data processing code is a bit mass. After some restructure, we will upload these scripts.
