### ISSUE TITLE
关于clipart

### ISSUE THREAD

**Issue by dipl123** [thuml/Transfer-Learning-Library#227]
作者您好，我下载的clipart数据集里面是没有trainval.tx这个文件的，请问一下本实验是怎么划分的呢。

**Comment by thucbx99** [comment]
是指Domain Adaptation Detection中Clipart的划分吗，可以直接下载我们提供的数据集，我印象中是直接使用全部的数据进行训练/测试，其中训练时不使用标签

**Comment by dipl123** [comment]
> 是指Domain Adaptation Detection中Clipart的划分吗，可以直接下载我们提供的数据集，我印象中是直接使用全部的数据进行训练/测试，其中训练时不使用标签

好的，谢谢，但是我没有找到您提供的数据集在哪下载
