### ISSUE TITLE
Dead URL's

### ISSUE THREAD

**Issue by shounakd56** [thuml/Transfer-Learning-Library#230]
Office-31 Dataset's URL's in 
Transfer-Learning-Library/tllib/vision/datasets/office31.py are dead

**Comment by yurithefury** [comment]
Yep, it seems like all of the dataset URLs are either dead or permission denied. For example:
GTA5: https://cloud.tsinghua.edu.cn/f/c77ff6fc4eea435791f4/?dl=1
Cityscapes: https://cloud.tsinghua.edu.cn/f/08745e798b16483db4bf/?dl=1
Office31: https://cloud.tsinghua.edu.cn/f/0ac1924f514b44788d1d/?dl=1

**Comment by zhuojinxin** [comment]
yes,who have back-up

**Comment by thucbx99** [comment]
Sorry for that. Recently, there are some problems with our cloud disk. To make matters worse, the GPU server where we backed up these datasets has recently been attacked and the associated data has also been deleted. We are working to recover these datasets.
