### ISSUE TITLE
您好 vision中的datasets的数据集链接全部都失效了，可以更新吗

### ISSUE THREAD

**Issue by Onenormler** [thuml/Transfer-Learning-Library#232]
原始数据集的格式和您的代码中给出的要求不一样，代码中的下载链接也已经失效了，比如Caltech101、OxfordFlowers102、DTD。
请问可以更新一下链接吗

**Comment by thucbx99** [comment]
抱歉由于云盘和本地服务器同时出现问题，我们的数据集目前都失效了，现在我们正在想办法解决

**Comment by ENW-cyy** [comment]
你好 想出办法了吗
