### ISSUE TITLE
broken download url

### ISSUE THREAD

**Issue by buble-pie** [thuml/Transfer-Learning-Library#236]
Hi, the url for cityscapes not working:
`Failed download. Trying https -> http instead. Downloading http://cloud.tsinghua.edu.cn/f/08745e798b16483db4bf/?dl=1 to data/cityscapes/image_list.zip`

**Comment by vladherasymenko** [comment]
Also, the URL for deeplabv2_resnet101.pth renders 
```
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by thucbx99** [comment]
Try this one for cityscapes dataset 
https://cloud.tsinghua.edu.cn/f/a23536bb8a724e91af39/?dl=1

**Comment by thucbx99** [comment]
The URL for deeplabv2_resnet101.pth works for me. Try once again might help.

**Comment by JackyZS** [comment]
Same problem for deeplab, 'deeplabv2_resnet101': 'https://cloud.tsinghua.edu.cn/f/2d9a7fc43ce34f76803a/?dl=1' return 404.

**Comment by Bavesh-B** [comment]
The URL for surreal and LSP dataset is not working.

**Comment by thucbx99** [comment]
Thanks for pointing this out. We are still working to fix these links.
