### ISSUE TITLE
关于使用自己的图像数据集

### ISSUE THREAD

**Issue by huanglongfei1** [thuml/Transfer-Learning-Library#237]
感谢您的开源项目，请问如果我想使用我自己的图像数据集进行一个图像二分类的任务，数据集组织形式类似于’data/source/0',‘data/source/1’;'data/target/0','data/target/1'，我可以使用pytorch里面的imagefolder生成的Dataloader代替您代码中的train_source_loader，train_target_loader,val_loader,以及testloader吗，还是需要使用ImageList呢？感谢帮助！

**Comment by thucbx99** [comment]
可以使用自定义的Dataloader
