### ISSUE TITLE
pip install -i https://test.pypi.org/simple/ tllib==0.4 连接超时

### ISSUE THREAD

**Issue by zhipeng-web** [thuml/Transfer-Learning-Library#239]
使用提供的pip命令安装时，总是显示连接超时
Looking in indexes: https://test.pypi.org/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tllib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tllib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tllib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tllib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))': /simple/tllib/
Could not fetch URL https://test.pypi.org/simple/tllib/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='test.pypi.org', port=443): Max retries exceeded with url: /simple/tllib/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))) - skipping
ERROR: Could not find a version that satisfies the requirement tllib==0.4 (from versions: none)
ERROR: No matching distribution found for tllib==0.4

**Comment by thucbx99** [comment]
您好，这里的版本因为数据集失效也不推荐使用了，暂时建议直接clone我们的repo到本地
