### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by cactusyh** [thuml/Transfer-Learning-Library#24]
Thanks for your great framework. Just wanna report a small typo. Data time will always be 0 because you updated data_time before loading data [here](https://github.com/thuml/Transfer-Learning-Library/blob/97f67c60095956b0d2206d48d729e4b51d39192a/examples/source_only.py#L127).

**Comment by JunguangJiang** [comment]
Thanks for your comments. I've noticed this typo and fix it in the dev branch, which will replace the main branch in a few months.
