### ISSUE TITLE
关于RSD论文中 特征矩阵的F范数

### ISSUE THREAD

**Issue by dby629** [thuml/Transfer-Learning-Library#240]
您好  请问RSD论文中figure1（b）具体是如何得到的？文中 “we use L2 regularization to change the Frobenius norm of feature matrix. "对于这句话不太理解，可以简单解释一下吗？非常感谢

**Comment by dby629** [comment]
我曾试图通过该邮箱联系作者，但是没有得到回复，请问还有其他途径吗？

**Comment by thucbx99** [comment]
可以试试这个邮箱chenxinyang@hit.edu.cn

**Comment by dby629** [comment]
好的 谢谢
