### ISSUE TITLE
疑惑询问

### ISSUE THREAD

**Issue by moonpaiff** [thuml/Transfer-Learning-Library#241]
您好，我想请问一下对于域自适应中，不应该是解决目标域没有标注的问题吗，为何在d_adapt中仍旧需要目标域的标注，那为何不直接用目标域的标注进行训练而要进行域自适应这一步呢，这是我的一个疑惑，希望可以得到您的回答谢谢！

**Comment by thucbx99** [comment]
您好，目标域上的标注我们始终是没有加入训练过程的，您这里指的目标域的标注具体实现在哪里呢？如果是category adapter的话，这是我生成的pseudo label而不是真实label
