### ISSUE TITLE
关于域自适应部分的疑惑提问

### ISSUE THREAD

**Issue by moonpaiff** [thuml/Transfer-Learning-Library#242]
您好，我想请问一下对于目标检测域自适应中，不是解决目标域没有标注的问题吗，为何在d_adapt中训练仍旧需要目标域的标注，那为何不直接用目标域的标注进行训练而要进行域自适应这一步呢，这是我的一个疑惑，希望可以得到您的回答谢谢！

**Comment by thucbx99** [comment]
你好，我理解这里的问题是在有target domain上模型产生的伪标签情况下，直接用这个伪标签训练检测器效果如何。我们发现由于domain gap的存在，target domain上由检测器输出的伪标签是非常不准确的，论文中也汇报了这样做的结果（Table 6），相比于d_adapt有很大的性能差异。

**Comment by moonpaiff** [comment]
您好，抱歉我可能没有将我的疑问描述清楚。我的疑问是，我在运行d_adapt时发现需要目标域的标注才能成功运行代码，可是域自适应所解决的问题是目标域没有标注的问题，那么为什么运行域自适应的程序时还需要目标域的标注呢？我所理解的域自适应不应该是利用有标注的源域和没有标注的目标域训练模型，从而得到一个可以在目标域上产生良好性能的模型吗，那么不应该直接将无标注的目标域送进去训练吗，为什么还是需要目标域的标注才能运行程序呢？希望我将疑问表达清楚了，并且非常希望得到您的回答！非常感谢您！

> 你好，我理解这里的问题是在有target domain上模型产生的伪标签情况下，直接用这个伪标签训练检测器效果如何。我们发现由于domain gap的存在，target domain上由检测器输出的伪标签是非常不准确的，论文中也汇报了这样做的结果（Table 6），相比于d_adapt有很大的性能差异。

**Comment by thucbx99** [comment]
这里只是为了实现上的方便，这样我们在开发算法的过程中可以实时监控d_adapt在目标域上的表现如何，例如做一些可视化case study。当然也可以把d_adapt实现为不需要目标域的标注就可以运行的形式，目前我们考虑大家可能主要还是会在Domain Adaptation的基准数据集上做实验或者改进，就保留了现在的实现
