### ISSUE TITLE
pip problem

### ISSUE THREAD

**Issue by didi226** [thuml/Transfer-Learning-Library#244]
When I use "pip install -i https://test.pypi.org/simple/ tllib==0.4"
出现问题ERROR: Could not find a version that satisfies the requirement webcolors (from tllib) (from versions: none)
ERROR: No matching distribution found for webcolors
python==3.9的版本可以正常的安装  python==3.10的版本存在这个问题。

**Comment by DylanCZW** [comment]
It's seems like the pip cannot get package from https://test.pypi.org/simple/. I use  pip install -i https://test.pypi.org/simple/ tllib==0.4 --extra-index-url  https://pypi.tuna.tsinghua.edu.cn/simple and it works.

**Comment by thucbx99** [comment]
> It's seems like the pip cannot get package from https://test.pypi.org/simple/. I use pip install -i https://test.pypi.org/simple/ tllib==0.4 --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple and it works.

Thanks for your advice!
