### ISSUE TITLE
关于域自适应的消融部分的疑惑

### ISSUE THREAD

**Issue by moonpaiff** [thuml/Transfer-Learning-Library#247]
您好，请问域自适应的目标检测中，category adaptation和bbox adaptation的消融实验应该如何进行，如何去除category adaptation或bbox adaptation来验证这两个模块的意义。非常希望得到您的回答，谢谢！

**Comment by thucbx99** [comment]
在相同的问题下回复您了哈，这个issue我就先close了

**Comment by moonpaiff** [comment]
好的，非常感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月27日(星期一) 中午1:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [thuml/Transfer-Learning-Library] 关于域自适应的消融部分的疑惑 (Issue #247)














 
在相同的问题下回复您了哈，这个issue我就先close了
