### ISSUE TITLE
Download link of deeplabv2

### ISSUE THREAD

**Issue by sleepyseal** [thuml/Transfer-Learning-Library#249]
It appears that the download link in 'tllib/vision/models/segmentation/deeplabv2.py' for the model 'deeplabv2_resnet101' is no longer working. Please update the download link.

**Comment by rgan19** [comment]
It doesn't work for me too, did anyone manage to get it running?

**Comment by sleepyseal** [comment]
Hi, it seems that their down link does not work. I download the weight from another project as a replacement. 
https://github.com/kazuto1011/deeplab-pytorch
Maybe you can try it.

**Comment by thucbx99** [comment]
> Hi, it seems that their down link does not work. I download the weight from another project as a replacement. https://github.com/kazuto1011/deeplab-pytorch Maybe you can try it.

Thanks for your advice!
