### ISSUE TITLE
numpy版本更新后np.float弃用

### ISSUE THREAD

**Issue by KevinCarpricorn** [thuml/Transfer-Learning-Library#253]
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.

**Comment by didi226** [comment]
I meet this problem, too

**Comment by thucbx99** [comment]
Thanks for pointing this out. You can modify it locally.
