### ISSUE TITLE
出视频讲解

### ISSUE THREAD

**Issue by xugliang** [thuml/Transfer-Learning-Library#255]
建议出一版视频对这个库有个讲解，我是新入门，完全看不懂示例，不知道该怎样用，一直弄不懂的话我也就没法用了，我相信还有很多人和我一样，所以想请问能否出个视频讲解

**Comment by thucbx99** [comment]
抱歉才回复，可以先参考一下我们的文档，库中大部分的代码都是原生PyTorch，因此也可以参考一下PyTorch的官方教程。出视频这个建议挺不错的，我会和实验室的师兄以及老板讨论一下
