### ISSUE TITLE
 The performance of the model decreases as the number of training times increases

### ISSUE THREAD

**Issue by zjuxiaobaiq** [thuml/Transfer-Learning-Library#257]
hi ,i try to run “a-dapt” on my own datasets. However, the performance decrease when i run “a-dapt” multiple times.  Could you give me some advices on what problem may happen?

**Comment by thucbx99** [comment]
I think it may be because the pseudo labels are not accurate and lead to error accumulation. Can you provide the evaluation result (such as mAP) of each round?
