### ISSUE TITLE
SURREAL and H3D dataset broken download link

### ISSUE THREAD

**Issue by MelekElloumi** [thuml/Transfer-Learning-Library#263]
So these cloud links are dead: https://cloud.tsinghua.edu.cn/f/b13604f06ff1445c830a/?dl=1
I read that the server got attacked and the files were deleted from one of your comments on a similar issue here.
I'm sorry to hear that.
Is there an update on the situation?

Meanwhile, I managed to download SURREAL dataset from elsewhere, but it has the original labels, not the processed ones that RegDA requires. Is it possible to provide only the processed labels of each run from train, valid, test set of this dataset?

**Comment by thucbx99** [comment]
Till now there are still many links that we fail to recover. For your question, I will contact the authors of RegDA recently to see if the preprocessing code is available.
