### ISSUE TITLE
The download URL used in the vision dataset is dead.

### ISSUE THREAD

**Issue by TaiseiYamana** [thuml/Transfer-Learning-Library#40]
Right now, when I clone this latest repository and run the tutorial, I get the following error:

![スクリーンショット 2021-03-30 16 08 47](https://user-images.githubusercontent.com/54575368/112947807-39fb4580-9172-11eb-9270-20ccb42b6ffc.png)

This referenced URL seems dead.
https://cloud.tsinghua.edu.cn/f/1f5646f39aeb4d7389b9/?dl=1

**Comment by JunguangJiang** [comment]
Sorry for this problem. Please refer to `dev`  branch, which has the latest URL.

**Comment by TaiseiYamana** [comment]
Thank you for your reply!

**Comment by Dayro-9** [comment]
Hello, I met the same error and used `!pip install --upgrade dalib`, but it didn't work. where can I find the latest URL?

**Comment by microhhh** [comment]
> Hello, I met the same error and used `!pip install --upgrade dalib`, but it didn't work. where can I find the latest URL?

For flexible use and modification, please git clone the library. Do not use pip install.

**Comment by Dayro-9** [comment]
> > Hello, I met the same error and used `!pip install --upgrade dalib`, but it didn't work. where can I find the latest URL?
> 
> For flexible use and modification, please git clone the library. Do not use pip install.

When I git clone the library and run the dann,  I get the following error:
![1](https://user-images.githubusercontent.com/59091691/115854510-e2908280-a45c-11eb-80d2-b286928951ce.png)
I've been receiving “ModuleNotFoundError: No module named 'common.vision'”. But I found this module in the cloned library， how to solve this error?

**Comment by microhhh** [comment]
> > > Hello, I met the same error and used `!pip install --upgrade dalib`, but it didn't work. where can I find the latest URL?
> > 
> > 
> > For flexible use and modification, please git clone the library. Do not use pip install.
> 
> When I git clone the library and run the dann, I get the following error:
> ![1](https://user-images.githubusercontent.com/59091691/115854510-e2908280-a45c-11eb-80d2-b286928951ce.png)
> I've been receiving “ModuleNotFoundError: No module named 'common.vision'”. But I found this module in the cloned library， how to solve this error?

Do not use pip install as line 12.
Add the project root path to PYTHON_PATH. And you should learn the basics of python.

**Comment by Dayro-9** [comment]
Thank you for your patience.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thuml/Transfer-Learning-Library"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thuml/Transfer-Learning-Library] The download URL used in the vision dataset is dead. (#40)





    
Hello, I met the same error and used !pip install --upgrade dalib, but it didn't work. where can I find the latest URL?
  
For flexible use and modification, please git clone the library. Do not use pip install.
  
When I git clone the library and run the dann, I get the following error:
 
 I've been receiving “ModuleNotFoundError: No module named 'common.vision'”. But I found this module in the cloned library， how to solve this error?
  
Do not use pip install as line 12.
 Add the project root path to PYTHON_PATH. And you should learn the basics of python.
