### ISSUE TITLE
I want to know about iters_per_epoch.

### ISSUE THREAD

**Issue by TaiseiYamana** [thuml/Transfer-Learning-Library#42]
add_argument does not include iters_per_epoch in the sample programs. What is the recommended iter_per_epoch?

**Comment by JunguangJiang** [comment]
In the scripts,  ‘-i 500’ means 500 iterations per epoch.

This parameter depends on the dataset size. For small datasets such as Office31, 500 is enough.

**Comment by TaiseiYamana** [comment]
Thank you for your comments!
I will refer to it for my experiment.

**Comment by kiranchari** [comment]
officehome has ~15k samples and default -i is 1000. This implies each epoch is actually going the through the dataset twice (default batch size is 32). So training for 30 epochs using the example script is actually equivalent to 60 epochs?

**Comment by JunguangJiang** [comment]
In each training, we will use two domains from office-home, and it would be difficult to go through them at the same time. Therefore, we use iters_per_epoch.
And the equivalence relation depends on which domain you are using.
