### ISSUE TITLE
DomainNet数据集中image_list文件错误

### ISSUE THREAD

**Issue by Aaron2Bin** [thuml/Transfer-Learning-Library#44]
尝试使用DomainNet数据集进行测试，发现其中image_list文件有误，使用dev分支中的链接下载发生同样的问题
![image](https://user-images.githubusercontent.com/49354436/115321398-4b0a0600-a1b6-11eb-81cd-527aa29de5bd.png)

**Comment by JunguangJiang** [comment]
Sorry for this problem, we have fixed this bug in the main branch.
