### ISSUE TITLE
关于MDD算法在Visda数据集上的复现

### ISSUE THREAD

**Issue by dingning97** [thuml/Transfer-Learning-Library#48]
MDD原文中（Bridging Theory and Algorithm for Domain Adaptation），Table3写道算法在visda数据集上Acc能达到74%+，请问可以分享一下超参数设置吗？比如说Initial LR、lr_gamma、lr_decay。十分感谢，最近我也在进行DA的工作，但是利用该lib开源代码的default setting无法reproduce，这样不太敢直接引用数据。
十分感谢！！！！

**Comment by dingning97** [comment]
贵组维护的MDD原repo（https://github.com/thuml/MDD/issues）似乎一直没有回复issues
Looking forward to reply and share !!!!! THX!

**Comment by JunguangJiang** [comment]
The following script should achieve ~74.9% on VisDA2017.
CUDA_VISIBLE_DEVICES=0 python mdd.py data/visda-2017 -d VisDA2017 -s Synthetic -t Real -a resnet50 --epochs 30 \
    --bottleneck-dim 1024 --seed 0 --center-crop --per-class-eval -b 36 --log logs/mdd/VisDA2017_resnet50

**Comment by JunguangJiang** [comment]
default setting无法reproduce,这是什么意思呢？
你可以把你的训练脚本，以及实验结果列举一下吗？

**Comment by dingning97** [comment]
![image](https://user-images.githubusercontent.com/57791074/117290841-df57b680-aea0-11eb-91ad-5fae8c6cb82d.png)
这是我的训练结果，用的是args里面的default的值，不过我设置seed为1了，我觉得seed的值对训练结果还是影响挺大的。
而且我没加--center-crop这个参数，我觉得这也可能是我没复现的原因；麻烦问一下，在visda数据集上用center-crop的方式训练，是否有助于涨点呀？
我再train一个，明天早晨我再来回复你呀~~

**Comment by dingning97** [comment]
![image](https://user-images.githubusercontent.com/57791074/117387948-5aaa7e00-af1c-11eb-9f9a-4d89f39be1d6.png)
这是我run的脚本CUDA_VISIBLE_DEVICES=0 python mdd.py data/visda-2017 -d VisDA2017 -s Synthetic -t Real -a resnet50 --epochs 100  -i 500 --bottleneck-dim 1024  -b 36 --log logs/mdd/VisDA2017 --seed 0 --center-crop
共训练5万个iter，best accuracy 74.21@iter27000，多跑几次应该差不多能跑出原文结果。

还训了一个没加--center-crop的模型，绿线，结果确实不好。

**Comment by JunguangJiang** [comment]
--center-crop对VisDA结果影响比较大，这也是MDD原实现中使用的方法
