### ISSUE TITLE
很好的项目，求多卡支持！！！

### ISSUE THREAD

**Issue by connorchen** [thuml/Transfer-Learning-Library#49]
dann.py 默认单卡执行，自行改了多卡设置，报了一些错误，求官方多卡支持啦~

**Comment by JunguangJiang** [comment]
最近在投稿，暂时没有时间补充多卡。你可以贴图放一下你碰到的报错？

**Comment by connorchen** [comment]
嗯，大概就是用 DataParallel 包装模型后，提示 DataParallel 不存在 get_parameters 函数，我看 Classifier 类中是有实现get_parameters 的， 但是不知道怎么带入 DataParallel 中，才疏学浅 - _ - !。

我现在的实验就是基于单卡的运行正常，就是有点慢，期待您的多卡解决方案，感谢！

**Comment by JunguangJiang** [comment]
这个很好改，DataParallel类有个module属性，它可以访问到包装前的对象

**Comment by connorchen** [comment]
> 这个很好改，DataParallel类有个module属性，它可以访问到包装前的对象

万分感谢，我试下 O(∩_∩)O~~

**Comment by jingzhengli** [comment]
> > 这个很好改，DataParallel类有个module属性，它可以访问到包装前的对象
> 
> 万分感谢，我试下 O(∩_∩)O~~

老哥，我改成多卡也遇到你的同样的问题。你现在怎么访问的包装前的对象？
