### ISSUE TITLE
第一次接触领域自适应，请教如果有多个 target 该怎么训？

### ISSUE THREAD

**Issue by connorchen** [thuml/Transfer-Learning-Library#50]

**Comment by JunguangJiang** [comment]
如果是分类的multi-target，可以参考https://github.com/thuml/Transfer-Learning-Library/blob/master/examples/domain_adaptation/multi_source/source_only.py，multi-source稍微改一下就是multi-target了

**Comment by connorchen** [comment]
感谢！
