### ISSUE TITLE
请教下如何解决背景分类

### ISSUE THREAD

**Issue by connorchen** [thuml/Transfer-Learning-Library#51]
我的数据集中除了正常的类别外，还有背景一类，背景的话没办法做DA吧，那背景类别如何进行训练呢，还是单独搞一个二分类模型先，把背景过滤掉？

**Comment by JunguangJiang** [comment]
source上如果有背景类的话，可以尝试直接做DA，我之前试过用CDAN的话，效果就挺好。如果source上没有背景的话，可以把背景看做openset class，那么可以使用OSBP，这个算法库里也有

**Comment by connorchen** [comment]
> source上如果有背景类的话，可以尝试直接做DA，我之前试过用CDAN的话，效果就挺好。如果source上没有背景的话，可以把背景看做openset class，那么可以使用OSBP，这个算法库里也有

"source上如果有背景类的话，可以尝试直接做DA，我之前试过用CDAN的话，效果就挺好。" -- 这个指的是 ① source 有 bg 而 target 没有 bg；还是 ② source 有 bg ，target 也有 bg？如果是前者 ① 的话，意思就是当前 DA 算法是支持类别不对齐的吧？

**Comment by connorchen** [comment]
> > source上如果有背景类的话，可以尝试直接做DA，我之前试过用CDAN的话，效果就挺好。如果source上没有背景的话，可以把背景看做openset class，那么可以使用OSBP，这个算法库里也有
> 
> "source上如果有背景类的话，可以尝试直接做DA，我之前试过用CDAN的话，效果就挺好。" -- 这个指的是 ① source 有 bg 而 target 没有 bg；还是 ② source 有 bg ，target 也有 bg？如果是前者 ① 的话，意思就是当前 DA 算法是支持类别不对齐的吧？

万分感谢！ 学习了一下，OSBP 就是支持 类别不对齐的，应该可以解决我的问题
