### ISSUE TITLE
How to reproduce the results of AFN+MCC?

### ISSUE THREAD

**Issue by jingzhengli** [thuml/Transfer-Learning-Library#53]
Hi, Thanks for the standard code. 
I tried to reproduce the experimental results of the AFN+MCC on office-31 in the MCC paper, but the results got worse. So I would like to ask are there any tricks needed to train the AFN+MCC? thanks in advance : )

**Comment by jingzhengli** [comment]
To add, what should the parameters **trade_off** for those two loss terms, norm_loss and transfer_loss,  be set to, respectively?

**Comment by Jin-Ying** [comment]
Sorry for late response. I am one of the authors of MCC, thank you for your attention to our work.
For AFN + MCC, set the trade-off of entropy loss to 0.0 and temperature in MCC to 3.0. 
If you have any other problems, feel free to contact me.

**Comment by jingzhengli** [comment]
Thanks for your reply. This would be helpful for me. Thanks again for such a standard code~
