### ISSUE TITLE
Questions for the implementation of Maximum Mean Discrepancy

### ISSUE THREAD

**Issue by Lelouch-Ice** [thuml/Transfer-Learning-Library#54]
For the implementation of Maximum Mean Discrepancy, I found your code seems to only support number of source samples to be equal to the number of target samples? How to implement the code for the unequal conditions?

**Comment by JunguangJiang** [comment]
It is better if the number of source and target samples in each **batch** is equal.
In addition, our code does not require the size of source dataset and target **dataset** to be the same.
