### ISSUE TITLE
如何使用Transfer-Learning-Library實現Semi Domain Adaptation算法

### ISSUE THREAD

**Issue by e96031413** [thuml/Transfer-Learning-Library#55]
您好：

如果想使用Transfer-Learning-Library進行Semi-supervised Domain Adaptation大概可以往哪個方向修改呢？

也就是說，原本Unsupervised Domain Adaptation的Target domain訓練時並無任何label

如果想在訓練時給定Target domain少量的label(例如: 給Target domain 5%的label就好)

或許能提升performance

謝謝

**Comment by JunguangJiang** [comment]
抱歉，没有做过相关的实验，建议直接找半监督DA的论文。
如果要用算法库的算法，建议将有标注的数据放到source，无标注的放到target，然后使用MDD算法，直觉上这样的效果比较好。
