### ISSUE TITLE
Questions about dann

### ISSUE THREAD

**Issue by xiaoachen98** [thuml/Transfer-Learning-Library#65]
在DANN原论文中，源域标签使用0表示，目标域标签使用1表示，在您的实现中反了过来。我试了改为原论文中的表示，A2W准确率为90.3.下降了1%左右，您这种反过来设置域标签是正常的，还是有什么特殊目的呢？
![1628233581(1)](https://user-images.githubusercontent.com/56393454/128470434-ddb78454-2a91-4bfd-baa8-d67b931226d4.png)

**Comment by JunguangJiang** [comment]
二者没有区别。Office31数据量太小了，所以随机数种子不一样，结果都不一样，建议换成更大的数据集做实验，比如Office-Home或者DomainNet
