### ISSUE TITLE
Task loss in CYCADA script.

### ISSUE THREAD

**Issue by scey26** [thuml/Transfer-Learning-Library#69]
Thanks for sharing your amazing work.

By the way, i found your CYCADA script doesn't include the task loss in the original paper.
(https://github.com/thuml/Transfer-Learning-Library/blob/94340da84502015885a87f7f9d5d352832ededec/examples/domain_adaptation/segmentation/cycada.py)

Is it just simplified version?

It will be very appreciated that you let me know the reasons omitting the task losses.
(please give me the description)

Thank you!

**Comment by JunguangJiang** [comment]
Experimentally, we found that feature distribution alignment doesn't work well on **segmentation tasks**, while image translation (such as CycleGAN) or output distribution alignment (such as ADVENT) are more useful. By selecting a good hyper-paramenters for CycleGAN, our CYCADA script achieves a much higher mIoU than that of the original paper (see [benchmark](https://github.com/thuml/Transfer-Learning-Library/blob/master/docs/dalib/benchmarks/segmentation_da.rst)). 
If you can train a better model with ADDA task loss, you are welcome to contribute your code to this project.
