### ISSUE TITLE
关于学习率和学习策略

### ISSUE THREAD

**Issue by xiaoachen98** [thuml/Transfer-Learning-Library#74]
非常感谢您的工作！
我在使用您的代码库在VisDA2017数据集上进行多种方法复现时发现了一个共通的问题，虽然最终指标都能达到您表里贴的那样，但是测试集准确率都是在5个epoch左右就能达到峰值，之后逐渐浮动甚至有下降趋势，请问这是默认的现象吗（故意这么设置为了在对比收敛速度时占优）？ 有没有什么方法可以缓解这一问题？

**Comment by tsingcbx99** [comment]
您跑的是哪几个算法呀

**Comment by xiaoachen98** [comment]
mcc mdd self-ensemble dann 几乎都有这个现象

**Comment by tsingcbx99** [comment]
这不是我们故意设置的~，猜测原因是VisDA2017这个数据集的target domain和ImageNet比较接近，而我们一般都会使用ImageNet上pretrain过的模型。也就是说拿到的初始模型就是对这个任务有帮助的，随着训练的进行网络会遗忘掉一些ImageNet上训练时的有益特征，就出现了准确率的下降。我们会在最近尝试一下有没有解决方案
