### ISSUE TITLE
Cannot Install by pip install -e . (using setup.py)

### ISSUE THREAD

**Issue by YouJiacheng** [thuml/Transfer-Learning-Library#75]
In setup.py
```python
with open(path.join(here, 'dalib', '__init__.py')) as f:
    version = re.search(r'__version__ = \'(.*?)\'', f.read()).group(1)
```
However, `dalib/__init__.py` does not contain `__version__`
Using git blame, I find [this commit](https://github.com/thuml/Transfer-Learning-Library/commit/4cac5fde1e6263f53d683fb56f72d42a8c87d514) delete `__version__` from `__init__.py`

**Comment by tsingcbx99** [comment]
Thanks for the feedback. We recommand that you `git clone` our library directly for flexible use and modification (no need to install again after you have modifed `dalib` ). Also, installing through `setup.py` will be supported soon.

**Comment by YouJiacheng** [comment]
> Thanks for the feedback. We recommand that you `git clone` our library directly for flexible use and modification (no need to install again after you have modifed `dalib` ). Also, installing through `setup.py` will be supported soon.

`pip install -e` support flexible use and modification(no need to install again after modification), as well as make the library be imported any where. I think this is the best practice.

**Comment by tsingcbx99** [comment]
> 
> 
> > Thanks for the feedback. We recommand that you `git clone` our library directly for flexible use and modification (no need to install again after you have modifed `dalib` ). Also, installing through `setup.py` will be supported soon.
> 
> `pip install -e` support flexible use and modification(no need to install again after modification), as well as make the library be imported any where. I think this is the best practice.

Thanks and we wiil fix that soon ~
