### ISSUE TITLE
AttributeError: 'TTYOutStream' object has no attribute '_exc'

### ISSUE THREAD

**Issue by yrg23** [thuml/Transfer-Learning-Library#81]
After training phase, i keep getting this error, any help appreciated.

```
 File "C:\Users\-\torchy\tllib\examples\domain_adaptation\classification\dann.py", line 331, in <module>
    main(args)

  File "C:\Users\-\torchy\tllib\examples\domain_adaptation\classification\dann.py", line 154, in main
    logger.close()

  File "C:\Users\-\torchy\tllib\examples\domain_adaptation\classification\../../..\common\utils\logger.py", line 98, in close
    self.logger.close()

  File "C:\Users\-\torchy\tllib\examples\domain_adaptation\classification\../../..\common\utils\logger.py", line 26, in close
    self.terminal.close()

  File "C:\Users\-\torchy\lib\site-packages\ipykernel\iostream.py", line 428, in close
    if self._exc:

AttributeError: 'TTYOutStream' object has no attribute '_exc'
```

pip list:

Package           Version
----------------- -----------
backcall          0.2.0
cloudpickle       2.0.0
colorama          0.4.4
cycler            0.10.0
Cython            0.29.24
debugpy           1.5.0
decorator         5.1.0
ipykernel         6.4.1
ipython           7.28.0
ipython-genutils  0.2.0
jedi              0.18.0
joblib            1.1.0
jupyter-client    6.1.12
jupyter-core      4.8.1
kiwisolver        1.3.2
matplotlib        3.4.3
matplotlib-inline 0.1.3
numpy             1.21.2
parso             0.8.2
pickleshare       0.7.5
Pillow            8.4.0
pip               21.3
prettytable       2.2.1
prompt-toolkit    3.0.20
Pygments          2.10.0
pyparsing         2.4.7
python-dateutil   2.8.2
pywin32           302
pyzmq             22.3.0
qdldl             0.1.5.post0
qpsolvers         1.7.1
quadprog          0.1.10
scikit-learn      1.0
scipy             1.7.1
setuptools        58.1.0
six               1.16.0
spyder-kernels    2.1.3
threadpoolctl     3.0.0
torch             1.7.1+cu110
torchaudio        0.7.2
torchvision       0.8.2+cu110
tornado           6.1
tqdm              4.62.3
traitlets         5.1.0
typing-extensions 3.10.0.2
wcwidth           0.2.5
webcolors         1.11.1
wheel             0.37.0

**Comment by JunguangJiang** [comment]
It seems that `sys.stdout.close()` doesn't work in your environment. It's very strange.
Sorry, we have not encountered such things before.
